version: '3.7'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: thumbsup-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: thumbsup
#    volumes:
#      - ./data:/var/lib/mysql

  redis:
    image: "redis:latest"
    container_name: thumbsup-redis

  web:
    build: .
    image: thumbsup-web-image
    container_name: thumbsup-web
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - db
    ports:
      - 9000:5000
      - 9001:5555

#  bot:
#    build: ./bot
#    image: thumbsup-bot-image
#    container_name: thumbsup-bot
#    restart: always
#    environment:
#      BOT_URL: t.me/ThumpsUpBot
#      BOT_TOKEN: 778885705:AAH-Bl8SRT0EHts3TZmY-5clOYHjjO7_Jew1000
#    depends_on:
#      - redis
#      - db
#      - web

# docker-compose rm -fs
# docker image rm $(docker images thumbsup* -q) -f
