"""jobs added date

Revision ID: 11c1a67c4f19
Revises: 756a9504ec7c
Create Date: 2018-11-26 14:30:13.030606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c1a67c4f19'
down_revision = '756a9504ec7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'date')
    # ### end Alembic commands ###
