"""jobs added state

Revision ID: 3e0c7141e934
Revises: 11c1a67c4f19
Create Date: 2018-11-26 14:45:13.993408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0c7141e934'
down_revision = '11c1a67c4f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'status')
    # ### end Alembic commands ###
