"""jobs

Revision ID: 756a9504ec7c
Revises: e78aad0ffacb
Create Date: 2018-11-26 14:22:39.745059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756a9504ec7c'
down_revision = 'e78aad0ffacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('like', sa.SmallInteger(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_url'), 'jobs', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_url'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
