"""proxies add column is_success

Revision ID: ad90a30853d9
Revises: eb5487beb4fa
Create Date: 2018-12-03 11:40:40.383311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad90a30853d9'
down_revision = 'eb5487beb4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxies', sa.Column('is_success', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxies', 'is_success')
    # ### end Alembic commands ###
