"""init

Revision ID: cbf34b6a16e6
Revises: 
Create Date: 2018-11-28 16:41:12.907333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf34b6a16e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('ordered_likes', sa.SmallInteger(), nullable=True),
    sa.Column('added_likes', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_url'), 'job', ['url'], unique=False)
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=15), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('count_used', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host', 'port', name='_host_port_uc')
    )
    op.create_index(op.f('ix_proxy_host'), 'proxy', ['host'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_proxy_host'), table_name='proxy')
    op.drop_table('proxy')
    op.drop_index(op.f('ix_job_url'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
